package xxokc.oracle.apps.okc.terms.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxOKCTermsTemplateApprovalHistoryVORowImpl extends OAViewRowImpl {
    public static final int TEMPLATEID = 0;
    public static final int STEPACTIONCODE = 1;
    public static final int STEPACTIONMEANING = 2;
    public static final int CREATEDBY = 3;
    public static final int CREATEDBYEMPNAME = 4;
    public static final int CREATIONDATE = 5;
    public static final int CREATIONDATEDSPLY = 6;

    /**This is the default constructor (do not remove)
     */
    public xxOKCTermsTemplateApprovalHistoryVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute TemplateId
     */
    public Number getTemplateId() {
        return (Number) getAttributeInternal(TEMPLATEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TemplateId
     */
    public void setTemplateId(Number value) {
        setAttributeInternal(TEMPLATEID, value);
    }

    /**Gets the attribute value for the calculated attribute StepActionCode
     */
    public String getStepActionCode() {
        return (String) getAttributeInternal(STEPACTIONCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StepActionCode
     */
    public void setStepActionCode(String value) {
        setAttributeInternal(STEPACTIONCODE, value);
    }

    /**Gets the attribute value for the calculated attribute StepActionMeaning
     */
    public String getStepActionMeaning() {
        return (String) getAttributeInternal(STEPACTIONMEANING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StepActionMeaning
     */
    public void setStepActionMeaning(String value) {
        setAttributeInternal(STEPACTIONMEANING, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedByEmpName
     */
    public String getCreatedByEmpName() {
        return (String) getAttributeInternal(CREATEDBYEMPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedByEmpName
     */
    public void setCreatedByEmpName(String value) {
        setAttributeInternal(CREATEDBYEMPNAME, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDateDsply
     */
    public String getCreationDateDsply() {
        return (String) getAttributeInternal(CREATIONDATEDSPLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDateDsply
     */
    public void setCreationDateDsply(String value) {
        setAttributeInternal(CREATIONDATEDSPLY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEMPLATEID:
            return getTemplateId();
        case STEPACTIONCODE:
            return getStepActionCode();
        case STEPACTIONMEANING:
            return getStepActionMeaning();
        case CREATEDBY:
            return getCreatedBy();
        case CREATEDBYEMPNAME:
            return getCreatedByEmpName();
        case CREATIONDATE:
            return getCreationDate();
        case CREATIONDATEDSPLY:
            return getCreationDateDsply();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
